spring:
  application:
    name: likelion-spring

  datasource:
    url: jdbc:mysql://likelion-database.c3wce8a2u84z.ap-northeast-2.rds.amazonaws.com:3306/likelion
    username: likelion
    password: whgnltjd987
